/**
 * Comprehensive Word List for Perpendicular Validation
 *
 * Contains:
 * 1. Islamic keywords (prophets, names of Allah, etc.)
 * 2. Filler words from generator-api
 * 3. Common English 2-5 letter words for crosswords
 *
 * Used to validate that perpendicular slots can be filled with real words.
 */

// Islamic keywords from sample-data and prophet-keywords
const ISLAMIC_WORDS = [
  // Prophets and related
  'ADAM', 'NUH', 'HUD', 'ISA', 'MUSA', 'ARK', 'AXE', 'CALF', 'CLAY', 'CROW',
  'FIRE', 'FISH', 'IRON', 'JUDI', 'NILE', 'WELL', 'WIND', 'AYYUB', 'DAWUD',
  'HARUN', 'HAWWA', 'IBLIS', 'IDRIS', 'ILYAS', 'INJIL', 'ISHAQ', 'JALUT',
  'KHIDR', 'MANNA', 'QABIL', 'SALIH', 'SARAH', 'STAFF', 'TORAH', 'WHALE',
  'YAHYA', 'YAQUB', 'YUNUS', 'YUSUF', 'ZABUR', 'HAGAR', 'HABIL', 'BURAQ',
  'DREAM', 'EGYPT', 'JESUS', 'MOSES', 'NOAH', 'MARY', 'JOB', 'JOHN',
  'JONAH', 'JACOB', 'DAVID', 'AARON', 'LOT', 'JINN',

  // Names of Allah
  'ALLAH', 'RAHMAN', 'RAHIM', 'MALIK', 'SALAM', 'AZIZ', 'KHALIQ', 'GHAFUR',
  'WAHAB', 'RAZZAQ', 'ALIM', 'SAMI', 'BASIR', 'HAKIM', 'WADUD', 'MAJID',
  'HAQQ', 'WAKIL', 'QADIR', 'AHAD', 'NUR', 'HADI', 'QAYYUM',

  // General Islamic terms
  'QURAN', 'SALAH', 'HAJJ', 'DUA', 'EID', 'FAJR', 'IQRA', 'HIRA', 'KAABA',
  'HIJRA', 'DHIKR', 'IMAM', 'MECCA', 'ISLAM', 'SAWM', 'TAWAF', 'WUDU',
  'HALAL', 'HARAM', 'SUNNI', 'SURAH', 'JIHAD', 'TAQWA', 'UMMAH', 'UMRAH',
  'FATWA', 'HAFIZ', 'GHUSL', 'IHRAM', 'IHSAN', 'MIRAJ', 'SHIRK', 'DAWAH',
  'DHUHR', 'SABR', 'NAFL', 'ISHA', 'ASR', 'BADR', 'UHUD', 'ANSAR',

  // Companions and others
  'ALI', 'UMAR', 'AISHA', 'BILAL', 'HAMZA', 'OMAR', 'ABBAS',
];

// Filler words from generator-api (themed for Islamic crosswords)
const FILLER_WORDS = [
  'PEACE', 'LIGHT', 'TRUTH', 'FAITH', 'GRACE', 'MERCY', 'HOPE', 'LOVE',
  'WISE', 'JUST', 'PURE', 'SOUL', 'GOOD', 'KIND', 'PRAY', 'FAST', 'GIVE',
  'READ', 'SEEK', 'PATH', 'GUIDE', 'BLESS', 'NOBLE',
];

// Common English 2-5 letter words (crossword-friendly)
const COMMON_ENGLISH_WORDS = [
  // 2-letter words (comprehensive Scrabble dictionary)
  'AA', 'AB', 'AD', 'AE', 'AG', 'AH', 'AI', 'AL', 'AM', 'AN', 'AR', 'AS',
  'AT', 'AW', 'AX', 'AY', 'BA', 'BE', 'BI', 'BO', 'BY', 'DA', 'DE', 'DI',
  'DO', 'ED', 'EF', 'EH', 'EL', 'EM', 'EN', 'ER', 'ES', 'ET', 'EW', 'EX',
  'FA', 'FE', 'GI', 'GO', 'GU', 'HA', 'HE', 'HI', 'HM', 'HO', 'HU', 'ID',
  'IF', 'IN', 'IS', 'IT', 'JA', 'JO', 'KA', 'KI', 'LA', 'LI', 'LO', 'MA',
  'ME', 'MI', 'MM', 'MO', 'MU', 'MY', 'NA', 'NE', 'NO', 'NU', 'OD', 'OE',
  'OF', 'OH', 'OI', 'OK', 'OM', 'ON', 'OO', 'OP', 'OR', 'OS', 'OU', 'OW',
  'OX', 'OY', 'PA', 'PE', 'PI', 'PO', 'QI', 'RE', 'SH', 'SI', 'SO', 'TA',
  'TE', 'TI', 'TO', 'UH', 'UM', 'UN', 'UP', 'UR', 'US', 'UT', 'WE', 'WO',
  'XI', 'XU', 'YA', 'YE', 'YO', 'ZA', 'ZO',

  // 3-letter words
  'ABA', 'ACE', 'ACT', 'ADA', 'ADD', 'AGE', 'AGO', 'AHA', 'AID', 'AIM',
  'AIR', 'ALA', 'ALL', 'AND', 'ANT', 'ANY', 'APE', 'ARC', 'ARE', 'ARM',
  'ART', 'ASH', 'ATE', 'AVA', 'AWE',
  'BAD', 'BAG', 'BAR', 'BAT', 'BAY', 'BED', 'BEE', 'BET', 'BIG', 'BIT',
  'BOW', 'BOX', 'BOY', 'BUD', 'BUG', 'BUS', 'BUT', 'BUY', 'CAB', 'CAN',
  'CAP', 'CAR', 'CAT', 'COB', 'COD', 'COG', 'COP', 'COT', 'COW', 'CRY',
  'CUB', 'CUD', 'CUP', 'CUR', 'CUT', 'DAB', 'DAD', 'DAM', 'DAY', 'DEN',
  'DEW', 'DID', 'DIE', 'DIG', 'DIM', 'DIP', 'DOC', 'DOE', 'DOG', 'DOT',
  'DRY', 'DUB', 'DUD', 'DUE', 'DUG', 'DYE', 'EAR', 'EAT', 'EEL', 'EGG',
  'ELF', 'ELK', 'ELM', 'EMU', 'END', 'ERA', 'ERR', 'EVE', 'EWE', 'EYE',
  'FAN', 'FAR', 'FAT', 'FAX', 'FED', 'FEE', 'FEW', 'FIG', 'FIN', 'FIT',
  'FIX', 'FLY', 'FOB', 'FOE', 'FOG', 'FOR', 'FOX', 'FRY', 'FUN', 'FUR',
  'GAB', 'GAG', 'GAP', 'GAS', 'GAY', 'GEL', 'GEM', 'GET', 'GIG', 'GIN',
  'GNU', 'GOB', 'GOD', 'GOT', 'GUM', 'GUN', 'GUT', 'GUY', 'GYM', 'HAD',
  'HAM', 'HAS', 'HAT', 'HAY', 'HEM', 'HEN', 'HER', 'HEW', 'HEX', 'HID',
  'HIM', 'HIP', 'HIS', 'HIT', 'HOB', 'HOD', 'HOG', 'HOP', 'HOT', 'HOW',
  'HUB', 'HUE', 'HUG', 'HUM', 'HUT', 'ICE', 'ICY', 'ILL', 'IMP', 'INK',
  'INN', 'ION', 'IRE', 'IRK', 'ITS', 'IVY', 'JAB', 'JAG', 'JAM', 'JAR',
  'JAW', 'JAY', 'JET', 'JIG', 'JOB', 'JOG', 'JOT', 'JOY', 'JUG', 'JUT',
  'KEG', 'KEN', 'KEY', 'KID', 'KIN', 'KIT', 'LAB', 'LAC', 'LAD', 'LAG',
  'LAP', 'LAW', 'LAY', 'LEA', 'LED', 'LEG', 'LET', 'LID', 'LIE', 'LIP',
  'LIT', 'LOG', 'LOT', 'LOW', 'LUG', 'MAD', 'MAN', 'MAP', 'MAR', 'MAT',
  'MAW', 'MAX', 'MAY', 'MEN', 'MET', 'MID', 'MIX', 'MOB', 'MOD', 'MOM',
  'MOP', 'MOW', 'MUD', 'MUG', 'MUM', 'NAB', 'NAG', 'NAP', 'NAY', 'NET',
  'NEW', 'NIL', 'NIP', 'NIT', 'NOB', 'NOD', 'NOR', 'NOT', 'NOW', 'NUB',
  'NUN', 'NUT', 'OAK', 'OAR', 'OAT', 'ODD', 'ODE', 'OFF', 'OFT', 'OHM',
  'OIL', 'OLD', 'ONE', 'OPT', 'ORB', 'ORE', 'OUR', 'OUT', 'OWE', 'OWL',
  'OWN', 'PAD', 'PAL', 'PAN', 'PAP', 'PAR', 'PAT', 'PAW', 'PAY', 'PEA',
  'PEG', 'PEN', 'PEP', 'PER', 'PET', 'PEW', 'PIE', 'PIG', 'PIN', 'PIT',
  'PLY', 'POD', 'POP', 'POT', 'POW', 'PRY', 'PUB', 'PUN', 'PUP', 'PUS',
  'PUT', 'RAD', 'RAG', 'RAM', 'RAN', 'RAP', 'RAT', 'RAW', 'RAY', 'RED',
  'REF', 'RIB', 'RID', 'RIG', 'RIM', 'RIP', 'ROB', 'ROD', 'ROE', 'ROT',
  'ROW', 'RUB', 'RUG', 'RUM', 'RUN', 'RUT', 'RYE', 'SAC', 'SAD', 'SAG',
  'SAP', 'SAT', 'SAW', 'SAY', 'SEA', 'SET', 'SEW', 'SHE', 'SHY', 'SIN',
  'SIP', 'SIR', 'SIS', 'SIT', 'SIX', 'SKI', 'SKY', 'SLY', 'SOB', 'SOD',
  'SON', 'SOP', 'SOT', 'SOW', 'SOY', 'SPA', 'SPY', 'STY', 'SUB', 'SUM',
  'SUN', 'SUP', 'TAB', 'TAD', 'TAG', 'TAN', 'TAP', 'TAR', 'TAT', 'TAX',
  'TEA', 'TEN', 'THE', 'THY', 'TIC', 'TIE', 'TIN', 'TIP', 'TOE', 'TON',
  'TOO', 'TOP', 'TOT', 'TOW', 'TOY', 'TRY', 'TUB', 'TUG', 'TWO', 'URN',
  'USE', 'VAN', 'VAT', 'VET', 'VIA', 'VIE', 'VOW', 'WAD', 'WAG', 'WAR',
  'WAS', 'WAX', 'WAY', 'WEB', 'WED', 'WEE', 'WET', 'WHO', 'WHY', 'WIG',
  'WIN', 'WIT', 'WOE', 'WOK', 'WON', 'WOO', 'WOW', 'YAK', 'YAM', 'YAP',
  'YAW', 'YEA', 'YES', 'YET', 'YEW', 'YIN', 'YIP', 'YOU', 'ZAP', 'ZED',
  'ZEN', 'ZIP', 'ZIT', 'ZOO',

  // 4-letter words
  'ABLE', 'ACHE', 'ACID', 'ACRE', 'AGED', 'AIDE', 'ALLY', 'ALSO', 'ALTO',
  'ANTI', 'ARCH', 'AREA', 'ARIA', 'ARMY', 'ARTS', 'AUNT', 'AUTO', 'AWAY',
  'AWRY', 'AXIS', 'BABY', 'BACK', 'BAIL', 'BAIT', 'BAKE', 'BALD', 'BALE',
  'BALL', 'BAND', 'BANE', 'BANG', 'BANK', 'BARB', 'BARE', 'BARK', 'BARN',
  'BASE', 'BASH', 'BATH', 'BEAD', 'BEAK', 'BEAM', 'BEAN', 'BEAR', 'BEAT',
  'BECK', 'BEEN', 'BEER', 'BELL', 'BELT', 'BEND', 'BENT', 'BERG', 'BEST',
  'BETA', 'BIAS', 'BIDE', 'BIKE', 'BILE', 'BILL', 'BIND', 'BIRD', 'BITE',
  'BLIP', 'BLOB', 'BLOC', 'BLOG', 'BLOW', 'BLUE', 'BLUR', 'BOAR', 'BOAT',
  'BODY', 'BOIL', 'BOLD', 'BOLT', 'BOMB', 'BOND', 'BONE', 'BOOK', 'BOOM',
  'BOOT', 'BORE', 'BORN', 'BOSS', 'BOTH', 'BOUT', 'BOWL', 'BRAG', 'BRED',
  'BREW', 'BRIM', 'BULK', 'BULL', 'BUMP', 'BURN', 'BURY', 'BUSH', 'BUST',
  'BUSY', 'BUZZ', 'CAFE', 'CAGE', 'CAKE', 'CALL', 'CALM', 'CAME', 'CAMP',
  'CANE', 'CAPE', 'CARD', 'CARE', 'CARP', 'CART', 'CASE', 'CASH', 'CASK',
  'CAST', 'CAVE', 'CELL', 'CHAR', 'CHAT', 'CHEF', 'CHEW', 'CHIC', 'CHIN',
  'CHIP', 'CHOP', 'CITE', 'CITY', 'CLAD', 'CLAM', 'CLAP', 'CLAW', 'CLIP',
  'CLOD', 'CLOG', 'CLUB', 'CLUE', 'COAL', 'COAT', 'COCK', 'CODE', 'COIL',
  'COIN', 'COLD', 'COLE', 'COLT', 'COMA', 'COMB', 'COME', 'CONE', 'COOK',
  'COOL', 'COPE', 'COPY', 'CORD', 'CORE', 'CORK', 'CORN', 'COST', 'COSY',
  'COUP', 'COVE', 'COZY', 'CRAB', 'CRAM', 'CREW', 'CRIB', 'CROP', 'CULT',
  'CURB', 'CURE', 'CURL', 'CUTE', 'DALE', 'DAME', 'DAMP', 'DARE', 'DARK',
  'DARN', 'DART', 'DASH', 'DATA', 'DATE', 'DAWN', 'DAYS', 'DEAD', 'DEAF',
  'DEAL', 'DEAN', 'DEAR', 'DEBT', 'DECK', 'DEED', 'DEEM', 'DEEP', 'DEER',
  'DEMO', 'DENT', 'DENY', 'DESK', 'DIAL', 'DICE', 'DIED', 'DIET', 'DIME',
  'DINE', 'DIRT', 'DISC', 'DISH', 'DISK', 'DIVE', 'DOCK', 'DOES', 'DOLE',
  'DOLL', 'DOME', 'DONE', 'DOOM', 'DOOR', 'DOPE', 'DOSE', 'DOVE', 'DOWN',
  'DOZE', 'DRAB', 'DRAG', 'DRAW', 'DREW', 'DRIP', 'DROP', 'DRUG', 'DRUM',
  'DUAL', 'DUCK', 'DUDE', 'DUEL', 'DUES', 'DUFF', 'DUKE', 'DULL', 'DULY',
  'DUMB', 'DUMP', 'DUNE', 'DUNK', 'DUSK', 'DUST', 'DUTY', 'EACH', 'EARL',
  'EARN', 'EASE', 'EAST', 'EASY', 'ECHO', 'EDGE', 'EDIT', 'ELSE', 'EMIT',
  'ENVY', 'EPIC', 'EURO', 'EVEN', 'EVER', 'EVIL', 'EXAM', 'EXIT', 'EXPO',
  'EYED', 'EYES', 'FACE', 'FACT', 'FADE', 'FAIL', 'FAIR', 'FAKE', 'FALL',
  'FAME', 'FANG', 'FARE', 'FARM', 'FATE', 'FAUN', 'FAWN', 'FEAR', 'FEAT',
  'FEED', 'FEEL', 'FEET', 'FELL', 'FELT', 'FEND', 'FERN', 'FEST', 'FEUD',
  'FIAT', 'FIEF', 'FILE', 'FILL', 'FILM', 'FIND', 'FINE', 'FIRE', 'FIRM',
  'FISH', 'FIST', 'FIVE', 'FLAG', 'FLAN', 'FLAP', 'FLAT', 'FLAW', 'FLAX',
  'FLEA', 'FLED', 'FLEE', 'FLEW', 'FLIP', 'FLIT', 'FLOG', 'FLOP', 'FLOW',
  'FOAM', 'FOCI', 'FOES', 'FOIL', 'FOLD', 'FOLK', 'FOND', 'FONT', 'FOOD',
  'FOOL', 'FOOT', 'FORD', 'FORE', 'FORK', 'FORM', 'FORT', 'FOUL', 'FOUR',
  'FOWL', 'FRAY', 'FREE', 'FRET', 'FROM', 'FUEL', 'FULL', 'FUME', 'FUND',
  'FUNK', 'FUSE', 'FUSS', 'GAIN', 'GAIT', 'GALA', 'GALE', 'GALL', 'GAME',
  'GANG', 'GAPE', 'GARB', 'GARY', 'GASH', 'GASP', 'GATE', 'GAVE', 'GAWK',
  'GAZE', 'GEAR', 'GENE', 'GERM', 'GIFT', 'GILD', 'GILL', 'GILT', 'GIRL',
  'GIST', 'GIVE', 'GLAD', 'GLAM', 'GLEE', 'GLEN', 'GLIB', 'GLOB', 'GLOM',
  'GLOP', 'GLOW', 'GLUE', 'GLUM', 'GLUT', 'GNAT', 'GNAW', 'GOAL', 'GOAT',
  'GOES', 'GOLD', 'GOLF', 'GONE', 'GONG', 'GOOD', 'GOON', 'GORE', 'GORY',
  'GOSH', 'GOTH', 'GOWN', 'GRAB', 'GRAD', 'GRAM', 'GRAY', 'GREW', 'GREY',
  'GRID', 'GRIM', 'GRIN', 'GRIP', 'GRIT', 'GROG', 'GROW', 'GRUB', 'GULF',
  'GULP', 'GUNK', 'GURU', 'GUSH', 'GUST', 'GUTS', 'HACK', 'HAIL', 'HAIR',
  'HAKE', 'HALE', 'HALF', 'HALL', 'HALT', 'HAND', 'HANG', 'HANK', 'HARD',
  'HARE', 'HARM', 'HARP', 'HASH', 'HASP', 'HATE', 'HATH', 'HAUL', 'HAVE',
  'HAWK', 'HAZE', 'HAZY', 'HEAD', 'HEAL', 'HEAP', 'HEAR', 'HEAT', 'HECK',
  'HEED', 'HEEL', 'HEIR', 'HELD', 'HELM', 'HELP', 'HEMP', 'HERD', 'HERE',
  'HERO', 'HERS', 'HIDE', 'HIGH', 'HIKE', 'HILL', 'HILT', 'HIND', 'HINT',
  'HIRE', 'HIVE', 'HOAX', 'HOCK', 'HOLD', 'HOLE', 'HOLY', 'HOME', 'HONE',
  'HOOD', 'HOOF', 'HOOK', 'HOOP', 'HOOT', 'HOPE', 'HORN', 'HOSE', 'HOST',
  'HOUR', 'HOWL', 'HUBS', 'HUFF', 'HUGE', 'HULK', 'HULL', 'HUMP', 'HUNG',
  'HUNK', 'HUNT', 'HURL', 'HURT', 'HUSH', 'HYMN', 'IBIS', 'ICED', 'ICON',
  'IDEA', 'IDLE', 'IDOL', 'INCH', 'INTO', 'IRON', 'ISLE', 'ITCH', 'ITEM',
  'JACK', 'JADE', 'JAIL', 'JAKE', 'JAMB', 'JANE', 'JAZZ', 'JEAN', 'JEANS',
  'JEEP', 'JEER', 'JELL', 'JERK', 'JEST', 'JIBE', 'JILT', 'JINX', 'JIVE',
  'JOBS', 'JOCK', 'JOIN', 'JOKE', 'JOLT', 'JOSH', 'JOWL', 'JOYS', 'JUDO',
  'JUGS', 'JUMP', 'JUNE', 'JUNK', 'JURY', 'JUST', 'JUTS', 'KALE', 'KEEN',
  'KEEP', 'KELP', 'KEPT', 'KEYS', 'KICK', 'KIDS', 'KILL', 'KILN', 'KILT',
  'KIND', 'KING', 'KINK', 'KISS', 'KITE', 'KNAB', 'KNEE', 'KNEW', 'KNIT',
  'KNOB', 'KNOT', 'KNOW', 'LABS', 'LACE', 'LACK', 'LACY', 'LADE', 'LADY',
  'LAID', 'LAIR', 'LAKE', 'LAMB', 'LAME', 'LAMP', 'LAND', 'LANE', 'LARD',
  'LARK', 'LASH', 'LASS', 'LAST', 'LATE', 'LAUD', 'LAVE', 'LAWN', 'LAWS',
  'LAYS', 'LAZY', 'LEAD', 'LEAF', 'LEAK', 'LEAN', 'LEAP', 'LEEK', 'LEFT',
  'LEGS', 'LEND', 'LENS', 'LENT', 'LESS', 'LEST', 'LEVY', 'LIAR', 'LICE',
  'LICK', 'LIED', 'LIEN', 'LIES', 'LIEU', 'LIFE', 'LIFT', 'LIKE', 'LILY',
  'LIMB', 'LIME', 'LIMP', 'LINE', 'LINK', 'LINT', 'LION', 'LIPS', 'LISP',
  'LIST', 'LIVE', 'LOAD', 'LOAF', 'LOAM', 'LOAN', 'LOBE', 'LOCK', 'LOCO',
  'LODE', 'LOFT', 'LOGO', 'LOGS', 'LONE', 'LONG', 'LOOK', 'LOOM', 'LOOP',
  'LOOT', 'LORD', 'LORE', 'LORN', 'LOSE', 'LOSS', 'LOST', 'LOTS', 'LOUD',
  'LOUR', 'LOUT', 'LOVE', 'LOWS', 'LUCK', 'LUGE', 'LULL', 'LUMP', 'LUNG',
  'LURE', 'LURK', 'LUSH', 'LUST', 'LYNX', 'MACE', 'MADE', 'MAID', 'MAIL',
  'MAIM', 'MAIN', 'MAKE', 'MALE', 'MALL', 'MALT', 'MANE', 'MANY', 'MAPS',
  'MARE', 'MARK', 'MARS', 'MART', 'MASH', 'MASK', 'MASS', 'MAST', 'MATE',
  'MATH', 'MAUL', 'MAYO', 'MAZE', 'MEAD', 'MEAL', 'MEAN', 'MEAT', 'MEEK',
  'MEET', 'MELD', 'MELT', 'MEMO', 'MEND', 'MENU', 'MERE', 'MESH', 'MESS',
  'MICA', 'MICE', 'MILD', 'MILE', 'MILK', 'MILL', 'MILS', 'MIME', 'MIND',
  'MINE', 'MINI', 'MINK', 'MINT', 'MINX', 'MIRE', 'MISS', 'MIST', 'MITE',
  'MITT', 'MOAN', 'MOAT', 'MOCK', 'MODE', 'MOLD', 'MOLE', 'MOLT', 'MONK',
  'MOOD', 'MOON', 'MOOR', 'MOOT', 'MORE', 'MORN', 'MOSS', 'MOST', 'MOTH',
  'MOVE', 'MUCH', 'MUCK', 'MUFF', 'MUGS', 'MULE', 'MULL', 'MUNG', 'MURK',
  'MUSE', 'MUSH', 'MUSK', 'MUST', 'MUTE', 'MYTH', 'NADA', 'NAIL', 'NAME',
  'NAPE', 'NAPS', 'NAVY', 'NEAR', 'NEAT', 'NECK', 'NEED', 'NEON', 'NERD',
  'NEST', 'NEWS', 'NEWT', 'NEXT', 'NICE', 'NICK', 'NIGH', 'NINE', 'NITS',
  'NODE', 'NODS', 'NOEL', 'NOIR', 'NONE', 'NOOK', 'NOON', 'NOPE', 'NORM',
  'NOSE', 'NOSY', 'NOTE', 'NOUN', 'NOVA', 'NUDE', 'NUKE', 'NULL', 'NUMB',
  'OAFS', 'OATH', 'OATS', 'OBEY', 'ODDS', 'ODOR', 'OFFS', 'OGLE', 'OGRE',
  'OILS', 'OILY', 'OKAY', 'OMEN', 'OMIT', 'ONCE', 'ONES', 'ONLY', 'ONTO',
  'ONUS', 'OOZE', 'OPAL', 'OPEN', 'OPTS', 'OPUS', 'ORAL', 'ORBS', 'ORCA',
  'ORES', 'OURS', 'OUST', 'OUTS', 'OVEN', 'OVER', 'OWED', 'OWES', 'OWLS',
  'OWNS', 'PACE', 'PACK', 'PACT', 'PADS', 'PAGE', 'PAID', 'PAIL', 'PAIN',
  'PAIR', 'PALE', 'PALM', 'PALS', 'PANE', 'PANG', 'PANS', 'PAPA', 'PARE',
  'PARK', 'PART', 'PASS', 'PAST', 'PATE', 'PATH', 'PATS', 'PAVE', 'PAWN',
  'PAWS', 'PAYS', 'PEAK', 'PEAR', 'PEAS', 'PEAT', 'PECK', 'PEEL', 'PEEP',
  'PEER', 'PEGS', 'PELT', 'PENS', 'PEON', 'PERK', 'PERM', 'PERT', 'PESO',
  'PEST', 'PETS', 'PICK', 'PIER', 'PIES', 'PIGS', 'PIKE', 'PILE', 'PILL',
  'PIMP', 'PINE', 'PING', 'PINK', 'PINS', 'PINT', 'PIPE', 'PISS', 'PITS',
  'PITY', 'PLAN', 'PLAY', 'PLEA', 'PLED', 'PLOD', 'PLOP', 'PLOT', 'PLOW',
  'PLOY', 'PLUG', 'PLUM', 'PLUS', 'PODS', 'POEM', 'POET', 'POKE', 'POLE',
  'POLL', 'POLO', 'POMP', 'POND', 'PONY', 'POOL', 'POOP', 'POOR', 'POPE',
  'POPS', 'PORE', 'PORK', 'PORT', 'POSE', 'POSH', 'POST', 'POSY', 'POTS',
  'POUR', 'POUT', 'PRAY', 'PREP', 'PREY', 'PRIM', 'PROD', 'PROM', 'PROP',
  'PROW', 'PRYS', 'PUBS', 'PUCK', 'PUDS', 'PUFF', 'PUGS', 'PULL', 'PULP',
  'PUMP', 'PUNS', 'PUNT', 'PUNY', 'PUPA', 'PUPS', 'PURE', 'PUSH', 'PUSS',
  'PUTS', 'PUTT', 'QUAD', 'QUAY', 'QUIZ', 'RACE', 'RACK', 'RAFT', 'RAGE',
  'RAGS', 'RAID', 'RAIL', 'RAIN', 'RAKE', 'RAMP', 'RAMS', 'RANG', 'RANK',
  'RANT', 'RAPE', 'RAPS', 'RAPT', 'RARE', 'RASH', 'RASP', 'RATE', 'RATS',
  'RAVE', 'RAYS', 'RAZE', 'READ', 'REAL', 'REAM', 'REAP', 'REAR', 'REDO',
  'REED', 'REEF', 'REEK', 'REEL', 'REFS', 'REIN', 'RELY', 'REND', 'RENT',
  'REST', 'RIBS', 'RICE', 'RICH', 'RIDE', 'RIDS', 'RIFE', 'RIFF', 'RIFT',
  'RIGS', 'RILE', 'RILL', 'RIMS', 'RIND', 'RING', 'RINK', 'RIOT', 'RIPE',
  'RIPS', 'RISE', 'RISK', 'RITE', 'ROAD', 'ROAM', 'ROAR', 'ROBE', 'ROBS',
  'ROCK', 'RODE', 'RODS', 'ROLE', 'ROLL', 'ROMP', 'ROOF', 'ROOK', 'ROOM',
  'ROOT', 'ROPE', 'ROPY', 'ROSE', 'ROSY', 'ROTS', 'ROUT', 'ROVE', 'ROWS',
  'RUBE', 'RUBS', 'RUBY', 'RUCK', 'RUDE', 'RUED', 'RUES', 'RUFF', 'RUGS',
  'RUIN', 'RULE', 'RUMP', 'RUMS', 'RUNG', 'RUNS', 'RUNT', 'RUSE', 'RUSH',
  'RUST', 'RUTS', 'SACK', 'SAFE', 'SAGA', 'SAGE', 'SAGS', 'SAID', 'SAIL',
  'SAKE', 'SALE', 'SALT', 'SAME', 'SAND', 'SANE', 'SANG', 'SANK', 'SAPS',
  'SASH', 'SASS', 'SAVE', 'SAWS', 'SAYS', 'SCAB', 'SCAM', 'SCAN', 'SCAR',
  'SEAL', 'SEAM', 'SEAR', 'SEAS', 'SEAT', 'SECT', 'SEED', 'SEEK', 'SEEM',
  'SEEN', 'SEEP', 'SEER', 'SEES', 'SELF', 'SELL', 'SEMI', 'SEND', 'SENT',
  'SEPT', 'SERA', 'SERE', 'SERF', 'SETS', 'SEWN', 'SEWS', 'SEXY', 'SHAG',
  'SHAM', 'SHED', 'SHIM', 'SHIN', 'SHIP', 'SHIV', 'SHMO', 'SHOD', 'SHOE',
  'SHOO', 'SHOP', 'SHOT', 'SHOW', 'SHUN', 'SHUT', 'SICK', 'SIDE', 'SIFT',
  'SIGH', 'SIGN', 'SILK', 'SILL', 'SILO', 'SILT', 'SIMP', 'SINE', 'SING',
  'SINK', 'SINS', 'SIPS', 'SIRE', 'SIRS', 'SITE', 'SITS', 'SIZE', 'SKEW',
  'SKID', 'SKIM', 'SKIN', 'SKIP', 'SKIT', 'SLAB', 'SLAG', 'SLAM', 'SLAP',
  'SLAT', 'SLAW', 'SLAY', 'SLED', 'SLEW', 'SLID', 'SLIM', 'SLIT', 'SLOB',
  'SLOE', 'SLOG', 'SLOP', 'SLOT', 'SLOW', 'SLUB', 'SLUE', 'SLUG', 'SLUM',
  'SLUR', 'SMOG', 'SNAG', 'SNAP', 'SNIP', 'SNIT', 'SNOB', 'SNOT', 'SNOW',
  'SNUB', 'SNUG', 'SOAK', 'SOAP', 'SOAR', 'SOBS', 'SOCK', 'SODA', 'SODS',
  'SOFA', 'SOFT', 'SOIL', 'SOLD', 'SOLE', 'SOLO', 'SOME', 'SONG', 'SONS',
  'SOON', 'SOOT', 'SOPS', 'SORE', 'SORT', 'SOUK', 'SOUP', 'SOUR', 'SOWN',
  'SOWS', 'SOYA', 'SPAN', 'SPAR', 'SPAS', 'SPAT', 'SPAY', 'SPEC', 'SPED',
  'SPIN', 'SPIT', 'SPOT', 'SPRY', 'SPUD', 'SPUN', 'SPUR', 'STAB', 'STAG',
  'STAR', 'STAT', 'STAY', 'STEM', 'STEP', 'STEW', 'STIR', 'STOA', 'STOP',
  'STOW', 'STUB', 'STUD', 'STUN', 'STYE', 'SUBS', 'SUCH', 'SUCK', 'SUDS',
  'SUED', 'SUES', 'SUET', 'SUIT', 'SULK', 'SUMO', 'SUMP', 'SUMS', 'SUNG',
  'SUNK', 'SUNS', 'SUPE', 'SURE', 'SURF', 'SWAB', 'SWAG', 'SWAM', 'SWAN',
  'SWAP', 'SWAT', 'SWAY', 'SWIG', 'SWIM', 'SWUM', 'SYNC', 'TABS', 'TACK',
  'TACO', 'TACT', 'TADS', 'TAGS', 'TAIL', 'TAKE', 'TALE', 'TALK', 'TALL',
  'TAME', 'TAMP', 'TANG', 'TANK', 'TAPE', 'TAPS', 'TARN', 'TARO', 'TARP',
  'TARS', 'TART', 'TASK', 'TAXI', 'TEAK', 'TEAL', 'TEAM', 'TEAR', 'TEAS',
  'TEAT', 'TECH', 'TEED', 'TEEM', 'TEEN', 'TELL', 'TEMP', 'TEND', 'TENS',
  'TENT', 'TERM', 'TERN', 'TEST', 'TEXT', 'THAN', 'THAT', 'THAW', 'THEE',
  'THEM', 'THEN', 'THEW', 'THEY', 'THIN', 'THIS', 'THUD', 'THUG', 'THUS',
  'TICK', 'TIDE', 'TIDY', 'TIED', 'TIER', 'TIES', 'TIFF', 'TIKI', 'TILE',
  'TILL', 'TILT', 'TIME', 'TINE', 'TING', 'TINS', 'TINT', 'TINY', 'TIPS',
  'TIRE', 'TOAD', 'TOES', 'TOFF', 'TOFU', 'TOGA', 'TOGS', 'TOIL', 'TOLD',
  'TOLL', 'TOMB', 'TOME', 'TONE', 'TONG', 'TONS', 'TONY', 'TOOK', 'TOOL',
  'TOOT', 'TOPS', 'TORE', 'TORN', 'TORT', 'TOSS', 'TOTE', 'TOTS', 'TOUR',
  'TOUT', 'TOWN', 'TOWS', 'TOYS', 'TRAM', 'TRAP', 'TRAY', 'TREE', 'TREK',
  'TREY', 'TRIG', 'TRIM', 'TRIO', 'TRIP', 'TROD', 'TROT', 'TRUE', 'TSAR',
  'TUBA', 'TUBE', 'TUBS', 'TUCK', 'TUFT', 'TUGS', 'TUNA', 'TUNE', 'TURF',
  'TURN', 'TUSK', 'TUTU', 'TWEE', 'TWIG', 'TWIN', 'TWIT', 'TWOS', 'TYPE',
  'TYPO', 'TYRO', 'UGLY', 'UNDO', 'UNIT', 'UNTO', 'UPON', 'URGE', 'URNS',
  'USED', 'USER', 'USES', 'VAIN', 'VALE', 'VAMP', 'VANE', 'VANS', 'VARY',
  'VASE', 'VAST', 'VATS', 'VEAL', 'VEER', 'VEIL', 'VEIN', 'VEND', 'VENT',
  'VERB', 'VERY', 'VEST', 'VETO', 'VETS', 'VIAL', 'VICE', 'VIED', 'VIES',
  'VIEW', 'VILE', 'VINE', 'VISA', 'VISE', 'VOID', 'VOLT', 'VOTE', 'VOWS',
  'WADE', 'WADS', 'WAFT', 'WAGE', 'WAGS', 'WAIL', 'WAIT', 'WAKE', 'WALK',
  'WALL', 'WAND', 'WANE', 'WANT', 'WARD', 'WARE', 'WARM', 'WARN', 'WARP',
  'WARS', 'WART', 'WARY', 'WASH', 'WASP', 'WAVE', 'WAVY', 'WAXY', 'WAYS',
  'WEAK', 'WEAL', 'WEAN', 'WEAR', 'WEDS', 'WEED', 'WEEK', 'WEEP', 'WELD',
  'WELL', 'WELT', 'WENT', 'WEPT', 'WERE', 'WEST', 'WHAM', 'WHAT', 'WHEN',
  'WHET', 'WHEY', 'WHIM', 'WHIP', 'WHIR', 'WHIT', 'WHIZ', 'WHOM', 'WICK',
  'WIDE', 'WIFE', 'WIGS', 'WILD', 'WILL', 'WILT', 'WILY', 'WIMP', 'WIND',
  'WINE', 'WING', 'WINK', 'WINS', 'WIPE', 'WIRE', 'WIRY', 'WISE', 'WISH',
  'WISP', 'WITH', 'WITS', 'WOKE', 'WOKS', 'WOLF', 'WOMB', 'WONT', 'WOOD',
  'WOOF', 'WOOL', 'WOOS', 'WORD', 'WORE', 'WORK', 'WORM', 'WORN', 'WORT',
  'WOVE', 'WOWS', 'WRAP', 'WREN', 'WRIT', 'YACK', 'YAKS', 'YAMS', 'YANG',
  'YANK', 'YAPS', 'YARD', 'YARN', 'YAWN', 'YAWP', 'YAWS', 'YEAH', 'YEAR',
  'YEAS', 'YELL', 'YELP', 'YENS', 'YEPS', 'YERK', 'YEWS', 'YIDS', 'YINS',
  'YIPE', 'YIPS', 'YOGI', 'YOKE', 'YOLK', 'YORE', 'YOUR', 'YOWL', 'YOWS',
  'YUAN', 'YUCK', 'YUKS', 'YULE', 'YUPS', 'ZANY', 'ZAPS', 'ZEAL', 'ZEBU',
  'ZEDS', 'ZEES', 'ZERO', 'ZEST', 'ZIGS', 'ZINC', 'ZING', 'ZIPS', 'ZITI',
  'ZONE', 'ZOOM', 'ZOOS',

  // 5-letter words
  'ABOUT', 'ABOVE', 'ABUSE', 'ACTOR', 'ACUTE', 'ADAPT', 'ADMIT', 'ADOPT',
  'ADULT', 'AFTER', 'AGAIN', 'AGENT', 'AGREE', 'AHEAD', 'AIMED', 'ALARM',
  'ALBUM', 'ALERT', 'ALIEN', 'ALIGN', 'ALIKE', 'ALIVE', 'ALLEY', 'ALLOW',
  'ALLOY', 'ALONE', 'ALONG', 'ALPHA', 'ALTER', 'AMONG', 'ANGEL', 'ANGER',
  'ANGLE', 'ANGRY', 'ANKLE', 'APART', 'APPLE', 'APPLY', 'ARENA', 'ARGUE',
  'ARISE', 'ARMOR', 'AROMA', 'ARRAY', 'ARROW', 'ASIDE', 'ASSET', 'ATLAS',
  'ATTIC', 'AUDIO', 'AUDIT', 'AVOID', 'AWAIT', 'AWAKE', 'AWARD', 'AWARE',
  'AWFUL', 'BACON', 'BADGE', 'BADLY', 'BAKER', 'BASED', 'BASIC', 'BASIN',
  'BASIS', 'BATCH', 'BEACH', 'BEAST', 'BEGAN', 'BEGIN', 'BEING', 'BELLY',
  'BELOW', 'BENCH', 'BERRY', 'BIBLE', 'BIRTH', 'BLACK', 'BLADE', 'BLAME',
  'BLANK', 'BLAST', 'BLEND', 'BLESS', 'BLIND', 'BLOCK', 'BLOND', 'BLOOD',
  'BLOOM', 'BLUES', 'BLUNT', 'BOARD', 'BOOST', 'BOOTH', 'BOUND', 'BRAIN',
  'BRAND', 'BRASS', 'BRAVE', 'BREAD', 'BREAK', 'BREED', 'BRICK', 'BRIDE',
  'BRIEF', 'BRING', 'BROAD', 'BROKE', 'BROOK', 'BROOM', 'BROTH', 'BROWN',
  'BRUSH', 'BUILD', 'BUILT', 'BUNCH', 'BURNT', 'BURST', 'BUYER', 'CABIN',
  'CABLE', 'CAMEL', 'CANAL', 'CANDY', 'CARGO', 'CARRY', 'CARVE', 'CATCH',
  'CAUSE', 'CEASE', 'CHAIN', 'CHAIR', 'CHALK', 'CHAMP', 'CHAOS', 'CHARM',
  'CHART', 'CHASE', 'CHEAP', 'CHEAT', 'CHECK', 'CHEEK', 'CHEER', 'CHEST',
  'CHIEF', 'CHILD', 'CHINA', 'CHORD', 'CHOSE', 'CHUNK', 'CIDER', 'CIGAR',
  'CINCH', 'CIRCA', 'CIVIC', 'CIVIL', 'CLAIM', 'CLAMP', 'CLASH', 'CLASS',
  'CLEAN', 'CLEAR', 'CLERK', 'CLICK', 'CLIFF', 'CLIMB', 'CLING', 'CLOCK',
  'CLONE', 'CLOSE', 'CLOTH', 'CLOUD', 'CLOWN', 'COACH', 'COAST', 'COCOA',
  'COLON', 'COLOR', 'COMET', 'COMIC', 'COMMA', 'CORAL', 'COUCH', 'COUGH',
  'COULD', 'COUNT', 'COURT', 'COVER', 'CRACK', 'CRAFT', 'CRANE', 'CRASH',
  'CRAWL', 'CRAZE', 'CRAZY', 'CREAM', 'CREEK', 'CREEP', 'CREST', 'CRIME',
  'CRISP', 'CROSS', 'CROWD', 'CROWN', 'CRUDE', 'CRUEL', 'CRUSH', 'CRUST',
  'CUBIC', 'CURVE', 'CYCLE', 'DAILY', 'DAIRY', 'DANCE', 'DATED', 'DEALT',
  'DEATH', 'DEBUT', 'DECAY', 'DECOR', 'DECOY', 'DELAY', 'DELTA', 'DENSE',
  'DEPOT', 'DEPTH', 'DERBY', 'DESKS', 'DETOX', 'DEVIL', 'DIARY', 'DIGIT',
  'DIRTY', 'DISCO', 'DITCH', 'DIVER', 'DIZZY', 'DOING', 'DONOR', 'DONUT',
  'DOUBT', 'DOUGH', 'DOZEN', 'DRAFT', 'DRAIN', 'DRAKE', 'DRAMA', 'DRANK',
  'DRAWL', 'DRAWN', 'DREAD', 'DRESS', 'DRIED', 'DRIFT', 'DRILL', 'DRINK',
  'DRIVE', 'DROIT', 'DROLL', 'DRONE', 'DROOL', 'DROOP', 'DROPS', 'DROSS',
  'DROVE', 'DROWN', 'DRUGS', 'DRUNK', 'DRYER', 'DRYLY', 'DUCHY', 'DULLY',
  'DUMMY', 'DUMPS', 'DUNCE', 'DUNES', 'DUSTY', 'DUTCH', 'DWARF', 'DWELL',
  'DYING', 'EAGER', 'EAGLE', 'EARLY', 'EARTH', 'EASED', 'EASEL', 'EATEN',
  'EATER', 'EBONY', 'EDGES', 'EERIE', 'EIGHT', 'ELBOW', 'ELDER', 'ELECT',
  'ELITE', 'ELOPE', 'ELUDE', 'EMAIL', 'EMBED', 'EMBER', 'EMPTY', 'ENDOW',
  'ENEMY', 'ENJOY', 'ENTER', 'ENTRY', 'EQUAL', 'EQUIP', 'ERASE', 'ERECT',
  'ERROR', 'ERUPT', 'ESSAY', 'ETHER', 'EVADE', 'EVENT', 'EVERY', 'EXACT',
  'EXALT', 'EXCEL', 'EXIST', 'EXPAT', 'EXTRA', 'EXULT', 'FABLE', 'FACET',
  'FAINT', 'FAIRY', 'FAITH', 'FALSE', 'FANCY', 'FATAL', 'FATTY', 'FAULT',
  'FAUNA', 'FAVOR', 'FEAST', 'FEIGN', 'FEMUR', 'FENCE', 'FERRY', 'FETCH',
  'FEVER', 'FIBER', 'FIBRE', 'FIELD', 'FIEND', 'FIERY', 'FIFTY', 'FIGHT',
  'FILTH', 'FINAL', 'FINCH', 'FIRST', 'FIXED', 'FIXER', 'FLAGS', 'FLAIR',
  'FLAKE', 'FLAME', 'FLANK', 'FLARE', 'FLASH', 'FLASK', 'FLATS', 'FLEET',
  'FLESH', 'FLICK', 'FLIER', 'FLING', 'FLINT', 'FLOAT', 'FLOCK', 'FLOOD',
  'FLOOR', 'FLORA', 'FLOUR', 'FLOWS', 'FLUID', 'FLUKE', 'FLUNG', 'FLUSH',
  'FLUTE', 'FOCAL', 'FOCUS', 'FOGGY', 'FOLLY', 'FORCE', 'FORGE', 'FORGO',
  'FORTH', 'FORTY', 'FORUM', 'FOSSIL', 'FOUND', 'FOXES', 'FOYER', 'FRAIL',
  'FRAME', 'FRANK', 'FRAUD', 'FREAK', 'FREED', 'FRESH', 'FRIAR', 'FRIED',
  'FRILL', 'FRISK', 'FRITZ', 'FRIZZ', 'FROCK', 'FROGS', 'FROLIC', 'FRONT',
  'FROST', 'FROTH', 'FROZE', 'FRUIT', 'FUDGE', 'FULLY', 'FUNGI', 'FUNKY',
  'FUNNY', 'FURRY', 'FUSSY', 'FUZZY', 'GAILY', 'GAINS', 'GAMMA', 'GASES',
  'GAUGE', 'GAUNT', 'GAUZE', 'GAUZY', 'GAVEL', 'GAWKY', 'GAZED', 'GEESE',
  'GENES', 'GENIE', 'GENRE', 'GIANT', 'GIFTS', 'GIRLY', 'GIRTH', 'GIVEN',
  'GIVER', 'GIVES', 'GIZMO', 'GLADE', 'GLAND', 'GLARE', 'GLASS', 'GLAZE',
  'GLEAM', 'GLEAN', 'GLIDE', 'GLINT', 'GLOAT', 'GLOBE', 'GLOOM', 'GLORY',
  'GLOSS', 'GLOVE', 'GNARLED', 'GNASH', 'GNOME', 'GOATS', 'GODLY', 'GOING',
  'GOLFER', 'GOOSE', 'GORGE', 'GRAFT', 'GRAIN', 'GRAND', 'GRANT', 'GRAPE',
  'GRAPH', 'GRASP', 'GRASS', 'GRATE', 'GRAVE', 'GRAVY', 'GRAZE', 'GREAT',
  'GREED', 'GREEK', 'GREEN', 'GREET', 'GRIEF', 'GRILL', 'GRIME', 'GRIND',
  'GROAN', 'GROOM', 'GROPE', 'GROSS', 'GROUP', 'GROVE', 'GROWL', 'GROWN',
  'GUARD', 'GUESS', 'GUEST', 'GUIDE', 'GUILD', 'GUILT', 'GUISE', 'GULCH',
  'GULLY', 'GUMMY', 'GUSTO', 'GUSTY', 'HABIT', 'HAIKU', 'HAIRS', 'HAIRY',
  'HALVE', 'HANDY', 'HAPPY', 'HARDY', 'HARSH', 'HASTE', 'HASTY', 'HATCH',
  'HATED', 'HATER', 'HAUNT', 'HAVEN', 'HAVOC', 'HAZEL', 'HEADS', 'HEADY',
  'HEARD', 'HEART', 'HEATH', 'HEAVE', 'HEAVY', 'HEDGE', 'HEIRS', 'HEIST',
  'HELLO', 'HENCE', 'HERBS', 'HERON', 'HILLS', 'HILLY', 'HINGE', 'HIPPO',
  'HIRED', 'HITCH', 'HOBBY', 'HOIST', 'HOLLY', 'HOMER', 'HONEY', 'HONOR',
  'HOOKS', 'HOPED', 'HORDE', 'HORSE', 'HOSTS', 'HOTEL', 'HOUND', 'HOURS',
  'HOUSE', 'HOVER', 'HUMAN', 'HUMID', 'HUMOR', 'HUMPS', 'HUMUS', 'HUNCH',
  'HUNKY', 'HURRY', 'HUSKY', 'HYENA', 'HYMNS', 'ICIER', 'ICILY', 'ICING',
  'IDEAL', 'IDEAS', 'IDIOM', 'IDIOT', 'IMAGE', 'IMPLY', 'INBOX', 'INCUR',
  'INDEX', 'INEPT', 'INERT', 'INFER', 'INNER', 'INPUT', 'INTER', 'INTRO',
  'IONIC', 'IRATE', 'IRKED', 'IRONY', 'IVORY', 'JACKS', 'JADED', 'JAUNT',
  'JAZZY', 'JEANS', 'JEERS', 'JELLY', 'JERKS', 'JERKY', 'JESUS', 'JEWEL',
  'JIFFY', 'JOINS', 'JOINT', 'JOKER', 'JOKES', 'JOLLY', 'JOLTS', 'JOUST',
  'JUDGE', 'JUICE', 'JUICY', 'JUMBO', 'JUMPS', 'JUMPY', 'JUNTA', 'JUROR',
  'KARMA', 'KAYAK', 'KEBAB', 'KEELS', 'KEEPS', 'KENNEL', 'KETCH', 'KEYED',
  'KICKS', 'KILLS', 'KINDS', 'KINGS', 'KIOSK', 'KISSS', 'KITES', 'KITTY',
  'KNACK', 'KNEAD', 'KNEED', 'KNEEL', 'KNEES', 'KNELT', 'KNIFE', 'KNOCK',
  'KNOLL', 'KNOTS', 'KNOWN', 'KNOWS', 'KUDOS', 'LABEL', 'LABOR', 'LACED',
  'LACKS', 'LADEN', 'LADLE', 'LAGER', 'LAKES', 'LAMBS', 'LAMPS', 'LANCE',
  'LANDS', 'LANES', 'LAPEL', 'LAPSE', 'LARGE', 'LARVA', 'LASER', 'LASSO',
  'LATCH', 'LATER', 'LATEX', 'LAUGH', 'LAYER', 'LAYUP', 'LEACH', 'LEADS',
  'LEAFY', 'LEAKS', 'LEAKY', 'LEANT', 'LEAPS', 'LEAPT', 'LEARN', 'LEASE',
  'LEASH', 'LEAST', 'LEAVE', 'LEDGE', 'LEECH', 'LEEKS', 'LEFTY', 'LEGAL',
  'LEMON', 'LEMUR', 'LENDS', 'LEVEL', 'LEVER', 'LIGHT', 'LILAC', 'LIMBO',
  'LIMBS', 'LIMIT', 'LINED', 'LINEN', 'LINER', 'LINES', 'LINGO', 'LINKS',
  'LIONS', 'LISTS', 'LITER', 'LITRE', 'LIVED', 'LIVEN', 'LIVER', 'LIVES',
  'LIVID', 'LLAMA', 'LOADS', 'LOAFS', 'LOANS', 'LOBBY', 'LOBES', 'LOCAL',
  'LOCKS', 'LODGE', 'LOFTY', 'LOGIC', 'LOGOS', 'LOINS', 'LONER', 'LOOKS',
  'LOONY', 'LOOPS', 'LOOPY', 'LOOSE', 'LOOTS', 'LORDS', 'LORRY', 'LOSER',
  'LOSES', 'LOSSS', 'LOTUS', 'LOUSE', 'LOUSY', 'LOUTS', 'LOVED', 'LOVER',
  'LOVES', 'LOWER', 'LOYAL', 'LUCID', 'LUCKY', 'LUMEN', 'LUMPS', 'LUMPY',
  'LUNAR', 'LUNCH', 'LUNGE', 'LUNGS', 'LURCH', 'LURED', 'LURES', 'LURID',
  'LURKS', 'LUSTY', 'LYING', 'LYMPH', 'LYNCH', 'LYRIC', 'MACHO', 'MACRO',
  'MADAM', 'MADLY', 'MAFIA', 'MAGIC', 'MAGMA', 'MAIDS', 'MAILS', 'MAIMS',
  'MAINS', 'MAIZE', 'MAJOR', 'MAKER', 'MAKES', 'MAMBO', 'MANGO', 'MANIA',
  'MANIC', 'MANOR', 'MAPLE', 'MARCH', 'MARES', 'MARKS', 'MARSH', 'MASKS',
  'MASON', 'MATCH', 'MATES', 'MATHS', 'MAXIM', 'MAYOR', 'MAZES', 'MEALS',
  'MEANS', 'MEANT', 'MEATY', 'MEDAL', 'MEDIA', 'MEDIC', 'MEETS', 'MELEE',
  'MELON', 'MELTS', 'MEMOS', 'MENDS', 'MENUS', 'MERCY', 'MERGE', 'MERIT',
  'MERRY', 'MESSY', 'METAL', 'METER', 'METRO', 'MICRO', 'MIDST', 'MIGHT',
  'MILLS', 'MIMIC', 'MINCE', 'MINDS', 'MINED', 'MINER', 'MINES', 'MINOR',
  'MINUS', 'MIRTH', 'MISER', 'MISSY', 'MISTY', 'MITES', 'MIXES', 'MOANS',
  'MOATS', 'MODEL', 'MODEM', 'MODES', 'MOIST', 'MOLAR', 'MOLDS', 'MOLDY',
  'MOLES', 'MOLTS', 'MOMMY', 'MONEY', 'MONKS', 'MONTH', 'MOODS', 'MOODY',
  'MOONS', 'MOOSE', 'MORAL', 'MORPH', 'MOTEL', 'MOTHS', 'MOTOR', 'MOTTO',
  'MOULD', 'MOUND', 'MOUNT', 'MOURN', 'MOUSE', 'MOUSY', 'MOUTH', 'MOVED',
  'MOVER', 'MOVES', 'MOVIE', 'MOWED', 'MOWER', 'MUCUS', 'MUDDY', 'MUFFS',
  'MUMMY', 'MUMPS', 'MUNCH', 'MURAL', 'MURKY', 'MUSHY', 'MUSIC', 'MUSKY',
  'MUSTY', 'MYTHS', 'NAILS', 'NAIVE', 'NAKED', 'NAMED', 'NAMER', 'NAMES',
  'NANNY', 'NASAL', 'NASTY', 'NAVAL', 'NAVEL', 'NEEDY', 'NERVE', 'NERVY',
  'NEVER', 'NEWER', 'NEWLY', 'NICHE', 'NIECE', 'NIGHT', 'NINTH', 'NITWIT',
  'NOBLE', 'NODDED', 'NOISE', 'NOISY', 'NOMAD', 'NORMS', 'NORTH', 'NOSEY',
  'NOTCH', 'NOTED', 'NOTES', 'NOVEL', 'NUDGE', 'NURSE', 'NUTTY', 'NYLON',
  'NYMPH', 'OAKEN', 'OASIS', 'OCCUR', 'OCEAN', 'OCTET', 'ODDLY', 'OFFED',
  'OFFER', 'OFTEN', 'OILED', 'OILER', 'OLDER', 'OLIVE', 'ONSET', 'OPERA',
  'OPTIC', 'ORBIT', 'ORDER', 'ORGAN', 'OSCAR', 'OTHER', 'OTTER', 'OUGHT',
  'OUNCE', 'OUTDO', 'OUTED', 'OUTER', 'OUTGO', 'OVARY', 'OVERT', 'OWING',
  'OWNED', 'OWNER', 'OXIDE', 'OZONE', 'PACED', 'PACER', 'PACES', 'PACKS',
  'PADRE', 'PAGAN', 'PAGES', 'PAINS', 'PAINT', 'PAIRS', 'PALMS', 'PALSY',
  'PANDA', 'PANEL', 'PANES', 'PANIC', 'PANTS', 'PAPAL', 'PAPER', 'PARCH',
  'PARKS', 'PARSE', 'PARTS', 'PARTY', 'PASTA', 'PASTE', 'PASTY', 'PATCH',
  'PATIO', 'PAUSE', 'PAVED', 'PAYER', 'PEACE', 'PEACH', 'PEAKS', 'PEARL',
  'PEARS', 'PECKS', 'PEDAL', 'PEEKS', 'PEELS', 'PEEPS', 'PEERS', 'PENAL',
  'PENCE', 'PENNY', 'PERCH', 'PERIL', 'PERKS', 'PERKY', 'PERMS', 'PESOS',
  'PESTS', 'PETAL', 'PETTY', 'PHASE', 'PHONE', 'PHOTO', 'PIANO', 'PICKS',
  'PICKY', 'PIECE', 'PIERS', 'PIETY', 'PIGGY', 'PILOT', 'PIMPS', 'PINCH',
  'PINES', 'PINGS', 'PINTS', 'PIOUS', 'PIPED', 'PIPER', 'PIPES', 'PITCH',
  'PITHS', 'PITHY', 'PITON', 'PIVOT', 'PIXEL', 'PIXIE', 'PIZZA', 'PLACE',
  'PLAID', 'PLAIN', 'PLANE', 'PLANK', 'PLANS', 'PLANT', 'PLATE', 'PLAYS',
  'PLAZA', 'PLEAD', 'PLEAS', 'PLEAT', 'PLEDGE', 'PLIED', 'PLIES', 'PLODS',
  'PLOPS', 'PLOTS', 'PLOWS', 'PLOYS', 'PLUCK', 'PLUGS', 'PLUMB', 'PLUME',
  'PLUMP', 'PLUMS', 'PLUMS', 'PLUNGE', 'PLUNK', 'PLUSH', 'POACH', 'POEMS',
  'POETS', 'POINT', 'POISE', 'POKED', 'POKER', 'POKES', 'POLAR', 'POLES',
  'POLLS', 'PONDS', 'POPES', 'POPPY', 'PORCH', 'PORES', 'PORTS', 'POSED',
  'POSER', 'POSES', 'POSIT', 'POSTS', 'POUCH', 'POUND', 'POURS', 'POWER',
  'PRANK', 'PRAWN', 'PRAYS', 'PREEN', 'PRESS', 'PREYS', 'PRICE', 'PRICK',
  'PRIDE', 'PRIED', 'PRIES', 'PRIME', 'PRIMP', 'PRINT', 'PRIOR', 'PRISM',
  'PRIVY', 'PRIZE', 'PROBE', 'PRODS', 'PROMS', 'PRONE', 'PRONG', 'PROOF',
  'PROPS', 'PROSE', 'PROUD', 'PROVE', 'PROWL', 'PRUDE', 'PRUNE', 'PSALM',
  'PUBIC', 'PULLS', 'PULPS', 'PULSE', 'PUMPS', 'PUNCH', 'PUNKS', 'PUPIL',
  'PUPPY', 'PURGE', 'PURSE', 'PUSHY', 'PUTTY', 'PYGMY', 'QUACK', 'QUAFF',
  'QUAIL', 'QUALM', 'QUART', 'QUASI', 'QUEEN', 'QUEER', 'QUEST', 'QUEUE',
  'QUICK', 'QUIET', 'QUILL', 'QUILT', 'QUIRK', 'QUITE', 'QUOTA', 'QUOTE',
  'RABBI', 'RACER', 'RACES', 'RACKS', 'RADAR', 'RADIO', 'RADON', 'RAFTS',
  'RAGED', 'RAGES', 'RAIDS', 'RAILS', 'RAINS', 'RAINY', 'RAISE', 'RAKED',
  'RAKES', 'RALLY', 'RAMPS', 'RANCH', 'RANGE', 'RANKS', 'RAPID', 'RARER',
  'RATED', 'RATER', 'RATES', 'RATIO', 'RAZOR', 'REACH', 'REACT', 'READS',
  'READY', 'REALM', 'REAMS', 'REAPS', 'REARS', 'REBEL', 'RECAP', 'RECUR',
  'REEDS', 'REEFS', 'REEKS', 'REELS', 'REFER', 'REGAL', 'REIGN', 'REINS',
  'RELAX', 'RELAY', 'RELIC', 'REMIT', 'REMIX', 'RENAL', 'RENEW', 'RENTS',
  'REPAY', 'REPEL', 'REPLY', 'RERUN', 'RESET', 'RESIN', 'RESTS', 'RETRY',
  'REUSE', 'REVEL', 'REVUE', 'RHINO', 'RHYME', 'RIDER', 'RIDES', 'RIDGE',
  'RIFLE', 'RIFTS', 'RIGHT', 'RIGID', 'RIGOR', 'RINDS', 'RINGS', 'RINSE',
  'RIOTS', 'RIPEN', 'RIPER', 'RISEN', 'RISER', 'RISES', 'RISKS', 'RISKY',
  'RITES', 'RITZY', 'RIVAL', 'RIVER', 'RIVET', 'ROADS', 'ROAMS', 'ROARS',
  'ROAST', 'ROBED', 'ROBES', 'ROBIN', 'ROBOT', 'ROCKS', 'ROCKY', 'RODEO',
  'ROGUE', 'ROLES', 'ROLLS', 'ROMAN', 'ROMPS', 'ROOFS', 'ROOKY', 'ROOMS',
  'ROOMY', 'ROOST', 'ROOTS', 'ROPED', 'ROPES', 'ROSES', 'ROTOR', 'ROUGE',
  'ROUGH', 'ROUND', 'ROUSE', 'ROUTE', 'ROVER', 'ROWDY', 'ROWED', 'ROWER',
  'ROYAL', 'RULER', 'RULES', 'RUMOR', 'RUPEE', 'RURAL', 'RUSTY', 'SABER',
  'SABLE', 'SADLY', 'SAFER', 'SAFES', 'SAGES', 'SAINT', 'SAKES', 'SALAD',
  'SALES', 'SALON', 'SALSA', 'SALTY', 'SALVE', 'SALVO', 'SAMBA', 'SANDY',
  'SANER', 'SANKS', 'SANTA', 'SASSY', 'SATIN', 'SAUCE', 'SAUCY', 'SAUNA',
  'SAUTE', 'SAVED', 'SAVER', 'SAVES', 'SAVOR', 'SAVVY', 'SCALE', 'SCALP',
  'SCALY', 'SCAMP', 'SCAMS', 'SCANS', 'SCARE', 'SCARF', 'SCARY', 'SCENE',
  'SCENT', 'SCOFF', 'SCOLD', 'SCONE', 'SCOOP', 'SCOOT', 'SCOPE', 'SCORE',
  'SCORN', 'SCOUT', 'SCOWL', 'SCRAM', 'SCRAP', 'SCREW', 'SCRUB', 'SEALS',
  'SEAMS', 'SEAMY', 'SEARS', 'SEATS', 'SECTS', 'SEEDS', 'SEEDY', 'SEEKS',
  'SEEMS', 'SEEPS', 'SEIZE', 'SELLS', 'SENDS', 'SENSE', 'SEPIA', 'SERIF',
  'SERUM', 'SERVE', 'SETUP', 'SEVEN', 'SEVER', 'SEWER', 'SHADE', 'SHADY',
  'SHAFT', 'SHAKE', 'SHAKY', 'SHALE', 'SHALL', 'SHAME', 'SHAMS', 'SHAPE',
  'SHARD', 'SHARE', 'SHARK', 'SHARP', 'SHAVE', 'SHAWL', 'SHEAR', 'SHEDS',
  'SHEEN', 'SHEEP', 'SHEER', 'SHEET', 'SHEIK', 'SHELF', 'SHELL', 'SHIFT',
  'SHIMS', 'SHINE', 'SHINS', 'SHINY', 'SHIPS', 'SHIRE', 'SHIRK', 'SHIRT',
  'SHOCK', 'SHOES', 'SHONE', 'SHOOK', 'SHOOT', 'SHOPS', 'SHORE', 'SHORN',
  'SHORT', 'SHOTS', 'SHOUT', 'SHOVE', 'SHOWN', 'SHOWS', 'SHOWY', 'SHRED',
  'SHREW', 'SHRUB', 'SHRUG', 'SHUCK', 'SHUNS', 'SHUNT', 'SHUSH', 'SICKS',
  'SIDED', 'SIDES', 'SIEGE', 'SIGHS', 'SIGHT', 'SIGMA', 'SIGNS', 'SILKS',
  'SILKY', 'SILLS', 'SILLY', 'SINCE', 'SINEW', 'SINGE', 'SINGS', 'SINKS',
  'SIREN', 'SIRES', 'SISSY', 'SITES', 'SIXTH', 'SIXTY', 'SIZED', 'SIZER',
  'SIZES', 'SKATE', 'SKEET', 'SKEIN', 'SKIDS', 'SKIED', 'SKIER', 'SKIES',
  'SKILL', 'SKIMP', 'SKINS', 'SKIPS', 'SKIRT', 'SKITS', 'SKULK', 'SKULL',
  'SKUNK', 'SLABS', 'SLACK', 'SLAGS', 'SLAIN', 'SLAKE', 'SLAMS', 'SLANG',
  'SLANT', 'SLAPS', 'SLASH', 'SLATS', 'SLATE', 'SLAVE', 'SLAYS', 'SLEEK',
  'SLEEP', 'SLEET', 'SLEPT', 'SLICE', 'SLICK', 'SLIDE', 'SLIME', 'SLIMY',
  'SLING', 'SLINK', 'SLIPS', 'SLITS', 'SLOBS', 'SLOES', 'SLOPE', 'SLOPS',
  'SLOSH', 'SLOTH', 'SLOTS', 'SLOWS', 'SLUBS', 'SLUGS', 'SLUMS', 'SLUNG',
  'SLUNK', 'SLURP', 'SLURS', 'SLUSH', 'SLYLY', 'SMACK', 'SMALL', 'SMART',
  'SMASH', 'SMEAR', 'SMELL', 'SMELT', 'SMILE', 'SMIRK', 'SMITE', 'SMITH',
  'SMOCK', 'SMOKE', 'SMOKY', 'SNACK', 'SNAFU', 'SNAGS', 'SNAIL', 'SNAKE',
  'SNAKY', 'SNAPS', 'SNARE', 'SNARL', 'SNEAK', 'SNEER', 'SNIDE', 'SNIFF',
  'SNIPE', 'SNIPS', 'SNITS', 'SNOBS', 'SNOOP', 'SNORE', 'SNORT', 'SNOTS',
  'SNOUT', 'SNOWS', 'SNOWY', 'SNUBS', 'SNUCK', 'SNUFF', 'SNUGS', 'SOAKS',
  'SOAPS', 'SOAPY', 'SOARS', 'SOBER', 'SOCKS', 'SODAS', 'SOFAS', 'SOFTY',
  'SOGGY', 'SOILS', 'SOLAR', 'SOLED', 'SOLES', 'SOLID', 'SOLOS', 'SOLVE',
  'SONIC', 'SONGS', 'SONNY', 'SOOTH', 'SOOTS', 'SOOTY', 'SORRY', 'SORTS',
  'SOUGHT', 'SOULS', 'SOUND', 'SOUPS', 'SOUPY', 'SOURS', 'SOUTH', 'SOWED',
  'SOWER', 'SPACE', 'SPADE', 'SPANS', 'SPARE', 'SPARK', 'SPARS', 'SPASM',
  'SPAWN', 'SPEAK', 'SPEAR', 'SPECS', 'SPEED', 'SPELL', 'SPEND', 'SPENT',
  'SPICE', 'SPICY', 'SPIED', 'SPIEL', 'SPIES', 'SPIKE', 'SPIKY', 'SPILL',
  'SPINE', 'SPINS', 'SPINY', 'SPIRE', 'SPITE', 'SPITS', 'SPLAT', 'SPLIT',
  'SPOIL', 'SPOKE', 'SPOOF', 'SPOOK', 'SPOOL', 'SPOON', 'SPORE', 'SPORT',
  'SPOTS', 'SPOUT', 'SPRAIN', 'SPRAY', 'SPREE', 'SPRIG', 'SPRUNG', 'SPUDS',
  'SPUNK', 'SPURN', 'SPURS', 'SPURT', 'SQUAD', 'SQUAT', 'SQUAW', 'SQUIB',
  'SQUID', 'STABS', 'STACK', 'STAFF', 'STAGE', 'STAGS', 'STAID', 'STAIN',
  'STAIR', 'STAKE', 'STALE', 'STALK', 'STALL', 'STAMP', 'STAND', 'STANK',
  'STAPH', 'STARE', 'STARK', 'STARS', 'START', 'STASH', 'STATE', 'STAVE',
  'STAYS', 'STEAD', 'STEAK', 'STEAL', 'STEAM', 'STEEL', 'STEEP', 'STEER',
  'STEMS', 'STENCH', 'STEPS', 'STERN', 'STEWS', 'STICK', 'STIFF', 'STILL',
  'STILT', 'STING', 'STINK', 'STINT', 'STIRS', 'STOCK', 'STOIC', 'STOKE',
  'STOLE', 'STOMP', 'STONE', 'STONY', 'STOOD', 'STOOL', 'STOOP', 'STOPS',
  'STORE', 'STORK', 'STORM', 'STORY', 'STOUT', 'STOVE', 'STRAP', 'STRAW',
  'STRAY', 'STREP', 'STREW', 'STRIP', 'STROP', 'STRUT', 'STUCK', 'STUDS',
  'STUDY', 'STUFF', 'STUMP', 'STUNG', 'STUNK', 'STUNS', 'STUNT', 'STYLE',
  'SUAVE', 'SUCKS', 'SUDSY', 'SUEDE', 'SUGAR', 'SUITE', 'SUITS', 'SULKY',
  'SUNNY', 'SUPER', 'SURGE', 'SURLY', 'SUSHI', 'SWABS', 'SWAMP', 'SWANS',
  'SWAPS', 'SWARM', 'SWATH', 'SWATS', 'SWAYS', 'SWEAR', 'SWEAT', 'SWEEP',
  'SWEET', 'SWELL', 'SWEPT', 'SWIFT', 'SWIGS', 'SWILL', 'SWIMS', 'SWINE',
  'SWING', 'SWIPE', 'SWIRL', 'SWISH', 'SWISS', 'SWOON', 'SWOOP', 'SWORD',
  'SWORE', 'SWORN', 'SWUNG', 'SYRUP', 'TABLE', 'TABOO', 'TACIT', 'TACKS',
  'TACKY', 'TACOS', 'TAILS', 'TAINT', 'TAKEN', 'TAKER', 'TAKES', 'TALES',
  'TALKS', 'TALLY', 'TALON', 'TAMED', 'TAMER', 'TAMES', 'TANDEM', 'TANGS',
  'TANGY', 'TANKS', 'TAPED', 'TAPER', 'TAPES', 'TARDY', 'TARPS', 'TARRY',
  'TARTS', 'TASKS', 'TASTE', 'TASTY', 'TAUNT', 'TAWNY', 'TAXED', 'TAXES',
  'TAXIS', 'TEACH', 'TEAMS', 'TEARS', 'TEARY', 'TEASE', 'TECHS', 'TEDDY',
  'TEETH', 'TEMPO', 'TEMPS', 'TEMPT', 'TENDS', 'TENOR', 'TENSE', 'TENTH',
  'TENTS', 'TEPEE', 'TEPID', 'TERMS', 'TERNS', 'TERRA', 'TESTS', 'TEXTS',
  'THANK', 'THAWS', 'THEFT', 'THEIR', 'THEME', 'THICK', 'THIEF', 'THIGH',
  'THING', 'THINK', 'THINS', 'THIRD', 'THONG', 'THORN', 'THOSE', 'THREE',
  'THREW', 'THROB', 'THROW', 'THUDS', 'THUGS', 'THUMB', 'THUMP', 'TIARA',
  'TIDAL', 'TIDED', 'TIDES', 'TIGER', 'TIGHT', 'TILED', 'TILER', 'TILES',
  'TILTS', 'TIMED', 'TIMER', 'TIMES', 'TIMID', 'TINGE', 'TIPSY', 'TIRED',
  'TIRES', 'TITAN', 'TITLE', 'TITTY', 'TOAST', 'TODAY', 'TOFFS', 'TOGAS',
  'TOILS', 'TOKEN', 'TOLLS', 'TOMBS', 'TONES', 'TONGS', 'TONIC', 'TOOLS',
  'TOOTH', 'TOOTS', 'TOPIC', 'TOPSY', 'TORCH', 'TORSO', 'TORTS', 'TORUS',
  'TOTAL', 'TOTEM', 'TOUCH', 'TOUGH', 'TOURS', 'TOWED', 'TOWEL', 'TOWER',
  'TOWNS', 'TOXIC', 'TOXIN', 'TRACE', 'TRACK', 'TRACT', 'TRADE', 'TRAIL',
  'TRAIN', 'TRAIT', 'TRAMP', 'TRAMS', 'TRAPS', 'TRASH', 'TRAWL', 'TRAYS',
  'TREAD', 'TREAT', 'TREES', 'TREKS', 'TREND', 'TRESS', 'TRIAL', 'TRIBE',
  'TRICK', 'TRIED', 'TRIER', 'TRIES', 'TRILL', 'TRIMS', 'TRIOS', 'TRIPS',
  'TRITE', 'TROLL', 'TROMP', 'TROOP', 'TROPE', 'TROTS', 'TROUT', 'TROVE',
  'TRUCE', 'TRUCK', 'TRUDGE', 'TRULY', 'TRUMP', 'TRUNK', 'TRUSS', 'TRUST',
  'TRUTH', 'TUBES', 'TUCKS', 'TULIP', 'TUMOR', 'TUNED', 'TUNER', 'TUNES',
  'TUNIC', 'TURBO', 'TURDS', 'TURNS', 'TUTOR', 'TUTTI', 'TUTUS', 'TWAIN',
  'TWANG', 'TWEAK', 'TWEED', 'TWEET', 'TWERP', 'TWICE', 'TWIGS', 'TWILL',
  'TWINE', 'TWINS', 'TWIRL', 'TWIST', 'TYING', 'TYKES', 'TYPES', 'UDDER',
  'ULCER', 'ULTRA', 'UMBRA', 'UNCLE', 'UNCUT', 'UNDER', 'UNDID', 'UNDUE',
  'UNFED', 'UNFIT', 'UNIFY', 'UNION', 'UNITE', 'UNITS', 'UNITY', 'UNLIT',
  'UNMET', 'UNPIN', 'UNSAY', 'UNSET', 'UNTIE', 'UNTIL', 'UNWED', 'UNZIP',
  'UPPER', 'UPSET', 'URBAN', 'URGED', 'URGES', 'URINE', 'USAGE', 'USHER',
  'USING', 'USUAL', 'UTTER', 'UDDER', 'VAGUE', 'VALET', 'VALID', 'VALOR',
  'VALUE', 'VALVE', 'VAMPS', 'VANES', 'VAPID', 'VAPOR', 'VAULT', 'VAUNT',
  'VEERS', 'VEILS', 'VEINS', 'VEINY', 'VENOM', 'VENTS', 'VENUE', 'VERBS',
  'VERGE', 'VERSE', 'VEXED', 'VEXES', 'VIBES', 'VICAR', 'VIDEO', 'VIEWS',
  'VIGIL', 'VIGOR', 'VILER', 'VILLA', 'VINES', 'VINYL', 'VIOLA', 'VIOLS',
  'VIPER', 'VIRAL', 'VIRUS', 'VISOR', 'VISTA', 'VITAL', 'VIVID', 'VIXEN',
  'VOCAL', 'VODKA', 'VOGUE', 'VOICE', 'VOIDS', 'VOLTS', 'VOMIT', 'VOTED',
  'VOTER', 'VOTES', 'VOUCH', 'VOWED', 'VOWEL', 'VULVA', 'WACKY', 'WADED',
  'WADER', 'WADES', 'WAFER', 'WAFTS', 'WAGED', 'WAGER', 'WAGES', 'WAGON',
  'WAIFS', 'WAILS', 'WAIST', 'WAITS', 'WAIVE', 'WAKED', 'WAKEN', 'WAKES',
  'WALKS', 'WALLS', 'WALTZ', 'WANDS', 'WANED', 'WANES', 'WANTS', 'WARDS',
  'WARES', 'WARMS', 'WARNS', 'WARPS', 'WARTS', 'WARTY', 'WASHI', 'WASHY',
  'WASPS', 'WASTE', 'WATCH', 'WATER', 'WATTS', 'WAVED', 'WAVER', 'WAVES',
  'WAXED', 'WAXEN', 'WAXES', 'WEAKEN', 'WEAKER', 'WEAKLY', 'WEALTH', 'WEANS',
  'WEARS', 'WEARY', 'WEAVE', 'WEBBY', 'WEDGE', 'WEEDS', 'WEEDY', 'WEEKS',
  'WEIGH', 'WEIRD', 'WELDS', 'WELLS', 'WELSH', 'WELTS', 'WENCH', 'WENDS',
  'WHACK', 'WHALE', 'WHARF', 'WHEAT', 'WHEEL', 'WHELP', 'WHERE', 'WHICH',
  'WHIFF', 'WHILE', 'WHIMS', 'WHINE', 'WHINY', 'WHIPS', 'WHIRL', 'WHISK',
  'WHITE', 'WHITS', 'WHOLE', 'WHOMP', 'WHOOP', 'WHOSE', 'WICKS', 'WIDEN',
  'WIDER', 'WIDOW', 'WIDTH', 'WIELD', 'WIFED', 'WIFES', 'WIFEY', 'WIGGY',
  'WILDS', 'WILED', 'WILES', 'WILLS', 'WILLY', 'WILTS', 'WIMPS', 'WIMPY',
  'WINCE', 'WINCH', 'WINDS', 'WINDY', 'WINED', 'WINER', 'WINES', 'WINGS',
  'WINKS', 'WIPED', 'WIPER', 'WIPES', 'WIRED', 'WIRER', 'WIRES', 'WISED',
  'WISER', 'WISPS', 'WISPY', 'WITCH', 'WITHE', 'WITHS', 'WITTY', 'WIVES',
  'WIZEN', 'WOKEN', 'WOMAN', 'WOMEN', 'WOMB', 'WOODS', 'WOODY', 'WOOED',
  'WOOER', 'WOOFS', 'WOOLS', 'WOOLY', 'WOOZY', 'WORDS', 'WORDY', 'WORKS',
  'WORLD', 'WORMS', 'WORMY', 'WORRY', 'WORSE', 'WORST', 'WORTH', 'WOULD',
  'WOUND', 'WOVEN', 'WRACK', 'WRAPS', 'WRATH', 'WREAK', 'WRECK', 'WREST',
  'WRING', 'WRIST', 'WRITE', 'WRITS', 'WRONG', 'WROTE', 'WRUNG', 'YACHT',
  'YAHOO', 'YAMMR', 'YANKS', 'YARDS', 'YARNS', 'YAWNS', 'YEAHS', 'YEARN',
  'YEARS', 'YEAST', 'YELLS', 'YELPS', 'YIELD', 'YODEL', 'YOKES', 'YOLKS',
  'YOUNG', 'YOURS', 'YOUTH', 'YOWLS', 'YUMMY', 'YURTS', 'ZAPPY', 'ZAPPY',
  'ZEALS', 'ZEBRA', 'ZEROS', 'ZESTS', 'ZESTY', 'ZILCH', 'ZINCS', 'ZINGY',
  'ZONED', 'ZONER', 'ZONES', 'ZOOMS',
];

/**
 * All valid words for 5x5 crossword validation (2-5 letters).
 * Combines Islamic keywords, filler words, and common English words.
 * Deduplicated and normalized to uppercase.
 */
export const ALL_WORDS_2_5: string[] = (() => {
  const combined = [
    ...ISLAMIC_WORDS,
    ...FILLER_WORDS,
    ...COMMON_ENGLISH_WORDS,
  ];

  // Deduplicate, normalize to uppercase, filter to 2-5 letters
  const uniqueWords = new Set<string>();
  for (const word of combined) {
    const upper = word.toUpperCase().trim();
    if (upper.length >= 2 && upper.length <= 5 && /^[A-Z]+$/.test(upper)) {
      uniqueWords.add(upper);
    }
  }

  return Array.from(uniqueWords).sort();
})();

/**
 * Islamic words only (for category checking).
 */
export const ISLAMIC_WORDS_SET = new Set(
  ISLAMIC_WORDS.map(w => w.toUpperCase().trim())
);

/**
 * Check if a word is an Islamic term.
 */
export function isIslamicWord(word: string): boolean {
  return ISLAMIC_WORDS_SET.has(word.toUpperCase().trim());
}

/**
 * Get word count by length for debugging.
 */
export function getWordCountsByLength(): Record<number, number> {
  const counts: Record<number, number> = {};
  for (const word of ALL_WORDS_2_5) {
    const len = word.length;
    counts[len] = (counts[len] || 0) + 1;
  }
  return counts;
}
